### ISSUE TITLE
Home, Features, DB Schema

### ISSUE THREAD

**Issue by paulobocanegra** [Eric-Mai-25/AirBnE#1]
# Wiki Page Home
- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a description sentence of the app
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page
---
# Feature List
- [x] Should have 7 Features.
    - [x] 3 of those are User Auth, Live Hosting on Render, and Production README.
    - [x] The other 4 are from the [Feature List](https://open.appacademy.io/learn/swe-campus-hybrid/full-stack-project/Feature-checklist) or they have clarified them with you
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each Feature
- [x] Correctly formatted
    - [x] Features are listed in an ordered list
    - [x] Each Feature is broken down into bullet points
---
# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details (primary and foreign keys, not null, indexed, unique)
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] table names, column names, and foreign keys are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded

**Comment by paulobocanegra** [comment]
Feature List:
We need to update your features: 
2, 3 and 4, are the same and different features at the same time. Let's change it to:

1. Hosting on Render
2. User Auth
3. Listings
4. Reservations
5. Reviews 
6. Dashboard (Profile page)
7.  Production Readme

Additional Features
8. Search

3. Listings
- Users can view a list of rentals. (Can be logged out)
- Users can view a Home details 
- etc... regarding a listing, no reviews/likes/reservations

4. Reservations
- Logged in users can reserve a listing
- Logged in users can update a reservation
- Logged in users can see a list a reservations they've had
- etc...

9. Reviews
- Guests can users can see all reviews
- Logged in users can review listing
- Logged in users can edit their review
- delete, etc

* For the purpose of cloning the main features of the app, don't allow users to Post a Listing. Just seed that data. Focus on Reservations & Reviews, then Likes.

**Comment by paulobocanegra** [comment]
DB Schema:
No such data type as primary key or foreign key, they are both bigint
a primary key is always id, no user_id, or table_id, just id.

Reference [this link](https://github.com/appacademy/bluebird/wiki/schema) for updates.

**Comment by paulobocanegra** [comment]
DB Schema:
no home table.
no payments table.

`users`
`listings`
`reservations`
`reviews`
`likes`

**Comment by Eric-Mai-25** [comment]
Ok I Fixed most of the issues that were listed. Would you like me to change the home table to listings table or would the be to confusing.

**Comment by paulobocanegra** [comment]
It is up to you, if the app is only renting homes, a homes table is good. I would call them listings but that is out of habit and a personal preference.

**Comment by Eric-Mai-25** [comment]
Ok I think I fixed the current issues. If the table names are still wrong am I supposed to copy the table exactly? I wanted to have some notes for me to reference.
